name: Tests with Selenium Grid

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Start Selenium Grid
        run: docker compose up -d

      - name: Wait for Grid
        run: |
          echo "Waiting for Grid to be ready..."
          timeout 90 bash -c 'until curl -sSf http://localhost:4444/wd/hub/status; do sleep 3; done'
          echo "Grid is ready!"
          docker ps --filter "name=selenium" --format "{{.Names}}"

      - name: Run Tests
        run: mvn clean verify -DbrowserName=chrome -Dheadless=true -DrunMode=remote || true

      - name: Generate Allure Report
        if: always()
        run: mvn io.qameta.allure:allure-maven:2.10.0:report

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/allure-maven-plugin
          publish_branch: gh-pages
          force_orphan: true

      - name: Cleanup
        if: always()
        run: docker compose down